# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.6.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /u01/upload
  # profile: D:/image/upload
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /exam-online-api
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  30MB
       # 设置总上传的文件大小
       max-request-size:  120MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
     database: 0 # Redis数据库索引（默认为0）
     # host: localhost # Redis服务器地址
     host: 10.200.121.66
     port: 6379 # Redis服务器连接端口
     password: Neusoft_Js123 # Redis服务器连接密码（默认为空）
     timeout: 20000 # 连接超时时间（毫秒）
     jedis:
        pool:
           max-active: -1 # 连接池最大连接数（使用负值表示没有限制）
           max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
           max-idle: 100 # 连接池中的最大空闲连接
           min-idle: 10 # 连接池中的最小空闲连接 
        
        
# 内容管理相关
cms:
  swipper:
    photo-path: /photo/swipper    
# 内容管理相关
  news:
    photo-path: /photo/news
# 文件管理相关
  fms:
    photo-path: /photo/fms
# 文件管理相关
  files:
    photo-path: /photo/files
# 流程附件相关
  workflow:
    file-path: /photo/ueditor
# 考试系统
  exam:
    photo-path: /photo/exam         
      
    
http:
  maxTotal: 300
  defaultMaxPerRoute: 100
  connectTimeout: 30000
  connectionRequestTimeout: 30000
  socketTimeout: 30000
  staleConnectionCheckEnabled: true
        
# 日志配置
logging:
  level:
    com.ruoyi: debug
    com.hig: debug
    org.springframework: warn



# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.ruoyi.**.domain,com.hig.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  # helperDialect: mysql
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /news-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
